### ISSUE TITLE
Add Facebook OpenGraph

### ISSUE THREAD

**Issue by tpun** [askdouble/askdouble.github.io#6]
<img width="404" alt="screen shot 2015-08-08 at 12 28 02 pm" src="https://cloud.githubusercontent.com/assets/77042/9149073/f16f2c1c-3dc8-11e5-9c5e-ace1f923d7b7.png">

**Comment by tpun** [comment]
https://developers.facebook.com/docs/sharing/webmasters#markup
https://developers.facebook.com/docs/sharing/best-practices

**Comment by tpun** [comment]
@hiukim  could you help look at why the `og:image` isn't getting pulled in from FB? (Try typing it in your FB sharing dialog.)

**Comment by hiukim** [comment]
@tpun might be due to the relative url we used. maybe try 
`<meta property="og:image" content="http://double.co/img/logo.long.png" />`

**Comment by tpun** [comment]
Don't think it has to do with relative URL.
http://ramsesoriginal.info/2015/03/21/facebook-open-graph-github-pages/
I did http://askdouble.github.io/ and it worked. So now I think http://double.co works now.
